server:
  port: 8080

spring:
  application:
    name: admin
  security:
    user:
      name: root
      password: 123456

  # 邮件设置
  mail:
    host: smtp.qq.com
    username: meet.parker@foxmail.com
    password: pamjnijkjkqdbbea
    properties:
      mail:
        smpt:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          #收件邮箱
          to: meet.carina@foxmail.com
          # 发件邮箱
          from: meet.parker@foxmail.com

# Eureka 公共配置
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@117.51.140.37:7500/eureka/,http://root:123456@47.93.54.81:7501/eureka/

management:
  endpoints:
    web:
      exposure:
        #yml加双引号，properties不用加
        include: "*"
  endpoint:
    health:
      ##默认是never
      show-details: ALWAYS
      enabled: true