server:
  port: 8080

spring:
  application:
    name: admin

  security:
    user:
      name: root
      password: 123456

  # 邮件设置
  mail:
    host: smtp.qq.com
    username: meet.parker@foxmail.com
    password: pamjnijkjkqdbbea
    properties:
      mail:
        smpt:
          auth: true
          starttls:
            enable: true
            required: true
  boot:
    admin:
      notify:
        mail:
          #收件邮箱
          to: meet.carina@foxmail.com
          # 发件邮箱
          from: meet.parker@foxmail.com
