server:
  port: 80

spring:
  application:
    name: GatewayZuul

# Eureka 公共配置
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@117.51.140.37:7500/eureka/,http://root:123456@47.93.54.81:7501/eureka/

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      enabled: true
#      show-details: always
#    routes:
#      enabled: true
#

#openfeign-consumer:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#provider:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

zuul:
  # 忽略 服务端 只暴露 消费端
  ignored-services:
    - provider
